[workspace]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
name = "gmn_adpater"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
requests = ">=2.32.5,<3"
daiquiri = ">=3.0.0,<4"
sqlalchemy = ">=2.0.45,<3"
sqlite = ">=3.51.1,<4"
pixi-pycharm = ">=0.0.10,<0.0.11"
pip = ">=25.3,<26"

[pypi-dependencies]
dataone-common = "*"
dataone-libclient = "*"
pyxb-x = "*"


[feature.dev.dependencies]
pytest = "*"
ruff = "*"
hatchling = "*"

[environments]
production = { solve-group = "prod" }
default = { features = ["dev"], solve-group = "prod" }
